import React, { createContext, useContext, useState, useEffect } from 'react';

// 13 Major Indian Languages with Native Script Labels
export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', locale: 'en-IN' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', locale: 'hi-IN' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', locale: 'te-IN' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', locale: 'ta-IN' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', locale: 'kn-IN' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', locale: 'ml-IN' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', locale: 'mr-IN' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', locale: 'gu-IN' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', locale: 'bn-IN' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', locale: 'pa-IN' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', locale: 'or-IN' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', locale: 'as-IN' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', locale: 'ur-IN' }
];

// Multilingual UI Translation Dictionary
const UI_TRANSLATIONS = {
  en: {
    portal_title: "LandLens-AI",
    ministry_sub: "Ministry of Rural Development • Gov of India",
    search_records: "Search Records",
    registration_status: "Registration Status",
    cadastral_gis: "Cadastral GIS Map",
    officer_workspace: "Officer Workspace",
    login: "Officer Login",
    logout: "Sign Out",
    hero_headline: "LandLens-AI",
    hero_sub: "AI-Powered Multilingual Land Record Digitization & Validation. Search, verify, and view official Record of Rights (RoR) certified across India.",
    search_placeholder: "Search by Owner Name, Survey Number, Village, or District in any Indian Language...",
    search_btn: "Search Records",
    voice_search_tooltip: "Voice Search (Speak in your preferred Indian language)",
    listening: "Listening... Please speak in",
    advanced_filters: "Advanced Filters",
    owner_name: "Owner Name",
    survey_no: "Survey / Khasra No.",
    village: "Village",
    district: "District",
    state: "State",
    land_area: "Land Area",
    status: "Status",
    view_details: "View Details",
    certified_ror: "Certified Record of Rights (RoR)",
    gov_verified: "Government Verified",
    ai_extracted: "AI Extracted",
    user_corrected: "Officer Corrected",
    needs_verification: "Needs Verification",
    lang_detected: "Detected Language",
    legal_disclaimer: "Legal Factuality Notice: Ownership and boundaries legally reside in the original registered document."
  },
  hi: {
    portal_title: "LandLens-AI",
    ministry_sub: "ग्रामीण विकास मंत्रालय • भारत सरकार",
    search_records: "अभिलेख खोजें",
    registration_status: "पंजीकरण स्थिति",
    cadastral_gis: "भूकर जीआईएस मानचित्र",
    officer_workspace: "अधिकारी कार्यक्षेत्र",
    login: "अधिकारी लॉगिन",
    logout: "लॉगआउट",
    hero_headline: "LandLens-AI",
    hero_sub: "एआई-संचालित बहुभाषी भू-अभिलेख डिजिटलीकरण और सत्यापन प्रणाली। भारत भर में प्रमाणित खतौनी/अधिकार अभिलेख खोजें और देखें।",
    search_placeholder: "भू-स्वामी का नाम, सर्वे संख्या, गाँव या ज़िला किसी भी भारतीय भाषा में खोजें...",
    search_btn: "अभिलेख खोजें",
    voice_search_tooltip: "आवाज़ से खोजें (अपनी मनपसंद भारतीय भाषा में बोलें)",
    listening: "सुन रहे हैं... कृपया बोलें",
    advanced_filters: "विस्तृत फ़िल्टर",
    owner_name: "भू-स्वामी का नाम",
    survey_no: "सर्वे / खसरा संख्या",
    village: "गाँव / मौजा",
    district: "ज़िला",
    state: "राज्य",
    land_area: "क्षेत्रफल (रकबा)",
    status: "स्थिति",
    view_details: "विवरण देखें",
    certified_ror: "प्रमाणित अधिकार अभिलेख (खतौनी)",
    gov_verified: "सरकार द्वारा प्रमाणित",
    ai_extracted: "एआई द्वारा निकाला गया",
    user_corrected: "अधिकारी द्वारा संशोधित",
    needs_verification: "सत्यापन आवश्यक",
    lang_detected: "पहचानी गई भाषा",
    legal_disclaimer: "कानूनी सूचना: प्रमाणित स्वामित्व और सीमाएं मूल पंजीकृत दस्तावेज़ के अनुसार ही मान्य हैं।"
  },
  te: {
    portal_title: "LandLens-AI",
    ministry_sub: "గ్రామీణాభివృద్ధి మంత్రిత్వ శాఖ • భారత ప్రభుత్వం",
    search_records: "రికార్డులు వెతకండి",
    registration_status: "రిజిస్ట్రేషన్ స్థితి",
    cadastral_gis: "భూ సర్వే GIS పటం",
    officer_workspace: "అధికారి వర్క్‌స్పేస్",
    login: "అధికారి లాగిన్",
    logout: "లాగ్అవుట్",
    hero_headline: "LandLens-AI",
    hero_sub: "AI ఆధారిత బహుభాషా భూ రికార్డుల డిజిటలైజేషన్ మరియు ధృవీకరణ వ్యవస్థ. దేశవ్యాప్తంగా ధృవీకరించబడిన పట్టాదారు హక్కుల రికార్డులు (RoR) చూడండి.",
    search_placeholder: "భూయజమాని పేరు, సర్వే నంబరు, గ్రామం లేదా జిల్లా పేరుతో వెతకండి...",
    search_btn: "వెతకండి",
    voice_search_tooltip: "వాయిస్ సెర్చ్ (మీ భారతీయ భాషలో మాట్లాడండి)",
    listening: "వింటున్నాము... దయచేసి మాట్లాడండి",
    advanced_filters: "మరిన్ని ఫిల్టర్లు",
    owner_name: "భూయజమాని పేరు",
    survey_no: "సర్వే నంబరు",
    village: "గ్రామం",
    district: "జిల్లా",
    state: "రాష్ట్రం",
    land_area: "భూవిస్తీర్ణము",
    status: "స్థితి",
    view_details: "వివరాలు చూడండి",
    certified_ror: "ధృవీకరించబడిన పట్టాదారు పాస్ పుస్తకం (RoR)",
    gov_verified: "ప్రభుత్వ ధృవీకృతం",
    ai_extracted: "AI ద్వారా సేకరించినది",
    user_corrected: "అధికారి సవరించినది",
    needs_verification: "ధృవీకరణ అవసరం",
    lang_detected: "గుర్తించిన భాష",
    legal_disclaimer: "చట్టపరమైన నోటీసు: యాజమాన్య హక్కులు మరియు సరిహద్దులు అసలు రిజిస్టర్డ్ పత్రం ప్రకారమే చెల్లుబాటు అవుతాయి."
  },
  ta: {
    portal_title: "LandLens-AI",
    ministry_sub: "ஊரக வளர்ச்சி அமைச்சகம் • இந்திய அரசு",
    search_records: "ஆவணங்கள் தேட",
    registration_status: "பதிவு நிலை",
    cadastral_gis: "நில வரைபடம் (GIS)",
    officer_workspace: "அதிகாரி பணிப்பகுதி",
    login: "அதிகாரி உள்நுழைவு",
    logout: "வெளியேறு",
    hero_headline: "LandLens-AI",
    hero_sub: "AI அடிப்படையிலான பலமொழி நில ஆவணமயமாக்கல் மற்றும் சரிபார்ப்பு அமைப்பு. பட்டா சிட்டா ஆவணங்களைத் தேடலாம்.",
    search_placeholder: "நில உரிமையாளர் பெயர், சர்வே எண், கிராமம் அல்லது மாவட்டம் உள்ளிடவும்...",
    search_btn: "தேடுக",
    voice_search_tooltip: "குரல் தேடல் (தமிழில் பேசலாம்)",
    listening: "கேட்கிறது... பேசவும்",
    advanced_filters: "மேம்பட்ட வடிகட்டிகள்",
    owner_name: "உரிமையாளர் பெயர்",
    survey_no: "சர்வே எண்",
    village: "கிராமம்",
    district: "மாவட்டம்",
    state: "மாநிலம்",
    land_area: "நிலப்பரப்பு",
    status: "நிலை",
    view_details: "விவரங்களை பார்க்க",
    certified_ror: "சான்றளிக்கப்பட்ட பட்டா ஆவணம்",
    gov_verified: "அரசு சரிபார்த்தது",
    ai_extracted: "AI பிரித்தெடுத்தது",
    user_corrected: "அதிகாரி திருத்தியது",
    needs_verification: "சரிபார்ப்பு தேவை",
    lang_detected: "கண்டறியப்பட்ட மொழி",
    legal_disclaimer: "சட்ட அறிவிப்பு: அசல் பதிவு செய்யப்பட்ட ஆவணமே சட்டபூர்வமானது."
  },
  mr: {
    portal_title: "LandLens-AI",
    ministry_sub: "ग्रामविकास मंत्रालय • भारत सरकार",
    search_records: "अभिलेख शोधा",
    registration_status: "नोंदणी स्थिती",
    cadastral_gis: "कॅडेस्ट्रल जीआयएस नकाशा",
    officer_workspace: "अधिकारी कार्यक्षेत्र",
    login: "अधिकारी लॉगिन",
    logout: "लॉगआउट",
    hero_headline: "LandLens-AI",
    hero_sub: "एआय-चालित बहुभाषिक जमीन नोंद डिजिटायझेशन प्रणाली. प्रमाणित ७/१२ व फेरफार अभिलेख शोधा.",
    search_placeholder: "खातेदाराचे नाव, गट क्रमांक / सर्व्हे नंबर, गाव किंवा जिल्हा शोधा...",
    search_btn: "शोध घ्या",
    voice_search_tooltip: "व्हॉइस सर्च (मराठीत बोला)",
    listening: "ऐकत आहे... कृपया बोला",
    advanced_filters: "प्रगत फिल्टर",
    owner_name: "खातेदाराचे नाव",
    survey_no: "गट क्रमांक / सर्व्हे नंबर",
    village: "गाव",
    district: "जिल्हा",
    state: "राज्य",
    land_area: "क्षेत्रफळ (गुंठे / एकर)",
    status: "स्थिती",
    view_details: "तपशील पहा",
    certified_ror: "प्रमाणित ७/१२ उतारा",
    gov_verified: "शासकीय प्रमाणित",
    ai_extracted: "एआय द्वारे काढलेले",
    user_corrected: "अधिकाऱ्याने दुरुस्त केलेले",
    needs_verification: "पडताळणी आवश्यक",
    lang_detected: "ओळखलेली भाषा",
    legal_disclaimer: "कायदेशीर सूचना: मूळ नोंदणीकृत दस्तऐवजच कायदेशीररित्या ग्राह्य मानला जाईल."
  },
  kn: {
    portal_title: "LandLens-AI",
    ministry_sub: "ಗ್ರಾಮೀಣಾಭಿವೃದ್ಧಿ ಸಚಿವಾಲಯ • ಭಾರತ ಸರ್ಕಾರ",
    search_records: "ದಾಖಲೆ ಹುಡುಕಿ",
    registration_status: "ನೋಂದಣಿ ಸ್ಥಿತಿ",
    cadastral_gis: "ಭೂಪಟ (GIS)",
    officer_workspace: "ಅಧಿಕಾರಿ ಕಾರ್ಯಕ್ಷೇತ್ರ",
    login: "ಅಧಿಕಾರಿ ಲಾಗಿನ್",
    logout: "ನಿರ್ಗಮಿಸಿ",
    hero_headline: "LandLens-AI",
    hero_sub: "AI ಆಧಾರಿತ ಬಹುಭಾಷಾ ಭೂ ದಾಖಲೆಗಳ ಗಣಕೀಕರಣ ವ್ಯವಸ್ಥೆ. ಪಹಣಿ ಹಾಗೂ ಆರ್‌ಒಆರ್ ದಾಖಲೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ.",
    search_placeholder: "ಭೂಮಾಲೀಕರ ಹೆಸರು, ಸರ್ವೆ ನಂಬರ್, ಗ್ರಾಮ ಅಥವಾ ಜಿಲ್ಲೆ ನಮೂದಿಸಿ...",
    search_btn: "ಹುಡುಕಿ",
    voice_search_tooltip: "ಧ್ವನಿ ಹುಡುಕಾಟ (ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿ)",
    listening: "ಆಲಿಸುತ್ತಿದೆ... ದಯವಿಟ್ಟು ಮಾತನಾಡಿ",
    advanced_filters: "ಸುಧಾರಿತ ಫಿಲ್ಟರ್‌ಗಳು",
    owner_name: "ಭೂಮಾಲೀಕರ ಹೆಸರು",
    survey_no: "ಸರ್ವೆ ನಂಬರ್",
    village: "ಗ್ರಾಮ",
    district: "ಜಿಲ್ಲೆ",
    state: "ರಾಜ್ಯ",
    land_area: "ವಿಸ್ತೀರ್ಣ",
    status: "ಸ್ಥಿತಿ",
    view_details: "ವಿವರ ವೀಕ್ಷಿಸಿ",
    certified_ror: "ಪ್ರಮಾಣೀಕೃತ ಪಹಣಿ (RTC / RoR)",
    gov_verified: "ಸರ್ಕಾರ ಪರಿಶೀಲಿಸಿದೆ",
    ai_extracted: "AI ಹೊರತೆಗೆದಿದೆ",
    user_corrected: "ಅಧಿಕಾರಿ ಸರಿಪಡಿಸಿದೆ",
    needs_verification: "ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿದೆ",
    lang_detected: "ಗುರುತಿಸಲಾದ ಭಾಷೆ",
    legal_disclaimer: "ಕಾನೂನು ಸೂಚನೆ: ಮೂಲ ನೋಂದಾಯಿತ ದಾಖಲೆಯು ಮಾತ್ರ ಕಾನೂನುಬದ್ಧವಾಗಿರುತ್ತದೆ."
  },
  bn: {
    portal_title: "LandLens-AI",
    ministry_sub: "পল্লী উন্নয়ন মন্ত্রক • ভারত সরকার",
    search_records: "রেকর্ড খুঁজুন",
    registration_status: "নিবন্ধন স্থিতি",
    cadastral_gis: "ক্যাডাস্ট্রাল জিআইএস মানচিত্র",
    officer_workspace: "কর্মকর্তা কর্মক্ষেত্র",
    login: "কর্মকর্তা লগইন",
    logout: "লগআউট",
    hero_headline: "LandLens-AI",
    hero_sub: "এআই-চালিত বহুভাষিক ভূমি রেকর্ড ডিজিটাইজেশন ব্যবস্থা। ভারত জুড়ে যাচাইকৃত খতিয়ান ও দাগ দেখুন।",
    search_placeholder: "জমির মালিকের নাম, দাগ নম্বর, মৌজা বা জেলা লিখুন...",
    search_btn: "অনুসন্ধান",
    voice_search_tooltip: "ভয়েস অনুসন্ধান (বাংলায় বলুন)",
    listening: "শুনছি... অনুগ্রহ করে বলুন",
    advanced_filters: "উন্নত ফিল্টার",
    owner_name: "মালিকের নাম",
    survey_no: "দাগ নম্বর / খতিয়ান",
    village: "মৌজা / গ্রাম",
    district: "জেলা",
    state: "রাজ্য",
    land_area: "জমির পরিমাণ",
    status: "স্থিতি",
    view_details: "বিবরণ দেখুন",
    certified_ror: "প্রমাণিত খতিয়ান রেকর্ড (RoR)",
    gov_verified: "সরকারি যাচাইকৃত",
    ai_extracted: "AI দ্বারা সংগৃহীত",
    user_corrected: "কর্মকর্তা সংশোধিত",
    needs_verification: "যাচাইকরণ প্রয়োজন",
    lang_detected: "সনাক্তকৃত ভাষা",
    legal_disclaimer: "আইনি বিজ্ঞপ্তি: মূল নিবন্ধিত দলিলই আইনত গ্রহণযোগ্য।"
  },
  gu: {
    portal_title: "LandLens-AI",
    ministry_sub: "ગ્રામીણ વિકાસ મંત્રાલય • ભારત સરકાર",
    search_records: "રેકોર્ડ શોધો",
    registration_status: "નોંધણી સ્થિતિ",
    cadastral_gis: "કેડેસ્ટ્રલ જીઆઇએસ નકશો",
    officer_workspace: "અધિકારી વર્કસ્પેસ",
    login: "અધિકારી લૉગિન",
    logout: "લૉગ આઉટ",
    hero_headline: "LandLens-AI",
    hero_sub: "AI-સંચાલિત બહુભાષીય જમીન દસ્તાવેજ ડિજિટાઇઝેશન. પ્રમાણિત ૭/૧૨ અને ૮-અ રેકોર્ડ શોધો.",
    search_placeholder: "જમીન માલિકનું નામ, સર્વે નંબર, ગામ અથવા જિલ્લો શોધો...",
    search_btn: "શોધો",
    voice_search_tooltip: "અવાજ દ્વારા શોધો (ગુજરાતીમાં બોલો)",
    listening: "સાંભળી રહ્યા છીએ... કૃપા કરીને બોલો",
    advanced_filters: "અદ્યતન ફિલ્ટર્સ",
    owner_name: "માલિકનું નામ",
    survey_no: "સર્વે નંબર",
    village: "ગામ",
    district: "જિલ્લો",
    state: "રાજ્ય",
    land_area: "ક્ષેત્રફળ",
    status: "સ્થિતિ",
    view_details: "વિગતો જુઓ",
    certified_ror: "પ્રમાણિત અધિકાર રેકોર્ડ (૭/૧૨)",
    gov_verified: "સરકાર દ્વારા ચકાસાયેલ",
    ai_extracted: "AI દ્વારા મેળવેલ",
    user_corrected: "અધિકારી દ્વારા સુધારેલ",
    needs_verification: "ચકાસણી જરૂરી છે",
    lang_detected: "શોધાયેલી ભાષા",
    legal_disclaimer: "કાનૂની સૂચના: મૂળ નોંધાયેલ દસ્તાવેજ કાયદેસર રીતે માન્ય ગણાશે."
  },
  ml: {
    portal_title: "LandLens-AI",
    ministry_sub: "ഗ്രാമവികസന മന്ത്രാലയം • ഭാരത സർക്കാർ",
    search_records: "രേഖകൾ തിരയുക",
    registration_status: "രജിസ്ട്രേഷൻ നില",
    cadastral_gis: "ലാൻഡ് മാപ്പ് (GIS)",
    officer_workspace: "ഓഫീസർ വർക്ക്‌സ്‌പേസ്",
    login: "ഓഫീസർ ലോഗിൻ",
    logout: "പുറത്തുകടക്കുക",
    hero_headline: "LandLens-AI",
    hero_sub: "AI അടിസ്ഥാനമാക്കിയുള്ള ബഹുഭാഷാ ഭൂമി രേഖാ പരിശോധനാ സംവിധാനം. തണ്ടപ്പേര്, സർവേ രേഖകൾ പരിശോധിക്കാം.",
    search_placeholder: "ഭൂവുടമയുടെ പേര്, സർവേ നമ്പർ, വില്ലേജ് തിരയുക...",
    search_btn: "തിരയുക",
    voice_search_tooltip: "വോയ്‌സ് സെർച്ച് (മലയാളത്തിൽ സംസാരിക്കുക)",
    listening: "ശ്രദ്ധിക്കുന്നു... സംസാരിക്കുക",
    advanced_filters: "കൂടുതൽ ഫിൽട്ടറുകൾ",
    owner_name: "ഭൂവുടമയുടെ പേര്",
    survey_no: "സർവേ നമ്പർ",
    village: "വില്ലേജ്",
    district: "ജില്ല",
    state: "സംസ്ഥാനം",
    land_area: "വിസ്തീർണ്ണം",
    status: "നില",
    view_details: "വിവരങ്ങൾ കാണുക",
    certified_ror: "സാക്ഷ്യപ്പെടുത്തിയ പട്ടയം രേഖ",
    gov_verified: "സർക്കാർ സ്ഥിരീകരിച്ചത്",
    ai_extracted: "AI എടുത്തത്",
    user_corrected: "ഓഫീസർ തിരുത്തിയത്",
    needs_verification: "പരിശോധന ആവശ്യമാണ്",
    lang_detected: "കണ്ടെത്തിയ ഭാഷ",
    legal_disclaimer: "നിയമപരമായ അറിയിപ്പ്: യഥാർത്ഥ രജിസ്റ്റർ ചെയ്ത രേഖയാണ് സാധുവായിരിക്കുന്നത്."
  },
  pa: {
    portal_title: "LandLens-AI",
    ministry_sub: "ਪੇਂਡੂ ਵਿਕਾਸ ਮੰਤਰਾਲਾ • ਭਾਰਤ ਸਰਕਾਰ",
    search_records: "ਰਿਕਾਰਡ ਖੋਜੋ",
    registration_status: "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਸਥਿਤੀ",
    cadastral_gis: "ਨਕਸ਼ਾ (GIS)",
    officer_workspace: "ਅਧਿਕਾਰੀ ਵਰਕਸਪੇਸ",
    login: "ਅਧਿਕਾਰੀ ਲਾਗਇਨ",
    logout: "ਲਾਗਆਉਟ",
    hero_headline: "LandLens-AI",
    hero_sub: "AI-ਸੰਚਾਲਿਤ ਬਹੁਭਾਸ਼ਾਈ ਜ਼ਮੀਨੀ ਰਿਕਾਰਡ ਡਿਜੀਟਾਈਜ਼ੇਸ਼ਨ ਸਿਸਟਮ। ਪ੍ਰਮਾਣਿਤ ਜਮ੍ਹਾਂਬੰਦੀ ਰਿਕਾਰਡ ਦੇਖੋ।",
    search_placeholder: "ਜ਼ਮੀਨ ਮਾਲਕ ਦਾ ਨਾਮ, ਖਸਰਾ / ਸਰਵੇ ਨੰਬਰ, ਪਿੰਡ ਜਾਂ ਜ਼ਿਲ੍ਹਾ ਖੋਜੋ...",
    search_btn: "ਖੋਜੋ",
    voice_search_tooltip: "ਆਵਾਜ਼ ਨਾਲ ਖੋਜੋ (ਪੰਜਾਬੀ ਵਿੱਚ ਬੋਲੋ)",
    listening: "ਸੁਣ ਰਿਹਾ ਹੈ... ਕਿਰਪਾ ਕਰਕੇ ਬੋਲੋ",
    advanced_filters: "ਫਿਲਟਰ",
    owner_name: "ਮਾਲਕ ਦਾ ਨਾਮ",
    survey_no: "ਖਸਰਾ / ਸਰਵੇ ਨੰਬਰ",
    village: "ਪਿੰਡ",
    district: "ਜ਼ਿਲ੍ਹਾ",
    state: "ਰਾਜ",
    land_area: "ਰਕਬਾ (ਕਨਾਲ/ਮਰਲੇ)",
    status: "ਸਥਿਤੀ",
    view_details: "ਵੇਰਵਾ ਦੇਖੋ",
    certified_ror: "ਪ੍ਰਮਾਣਿਤ ਜਮ੍ਹਾਂਬੰਦੀ (RoR)",
    gov_verified: "ਸਰਕਾਰ ਦੁਆਰਾ ਤਸਦੀਕਸ਼ੁਦਾ",
    ai_extracted: "AI ਦੁਆਰਾ ਕੱਢਿਆ ਗਿਆ",
    user_corrected: "ਅਧਿਕਾਰੀ ਦੁਆਰਾ ਸੋਧਿਆ ਗਿਆ",
    needs_verification: "ਤਸਦੀਕ ਦੀ ਲੋੜ ਹੈ",
    lang_detected: "ਪਛਾਣੀ ਗਈ ਭਾਸ਼ਾ",
    legal_disclaimer: "ਕਾਨੂੰਨੀ ਨੋਟਿਸ: ਅਸਲ ਰਜਿਸਟਰਡ ਦਸਤਾਵੇਜ਼ ਹੀ ਕਾਨੂੰਨੀ ਤੌਰ 'ਤੇ ਮੰਨਣਯੋਗ ਹੈ।"
  },
  or: {
    portal_title: "LandLens-AI",
    ministry_sub: "ଗ୍ରାମ୍ୟ ଉନ୍ନୟନ ମନ୍ତ୍ରଣାଳୟ • ଭାରତ ସରକାର",
    search_records: "ରେକର୍ଡ ଖୋଜନ୍ତୁ",
    registration_status: "ପଞ୍ଜୀକରଣ ସ୍ଥିତି",
    cadastral_gis: "ଜମି ମାନଚିତ୍ର (GIS)",
    officer_workspace: "ଅଧିକାରୀ କାର୍ଯ୍ୟକ୍ଷେତ୍ର",
    login: "ଅଧିକାରୀ ଲଗଇନ",
    logout: "ଲଗଆଉଟ",
    hero_headline: "LandLens-AI",
    hero_sub: "AI ଦ୍ୱାରା ବହୁଭାଷୀ ଜମି ରେକର୍ଡ ଡିଜିଟାଇଜେସନ ବ୍ୟବସ୍ଥା। ପ୍ରମାଣିତ ପଟ୍ଟା ଓ ଖତିଆନ ଦେଖନ୍ତୁ।",
    search_placeholder: "ଜମି ମାଲିକଙ୍କ ନାମ, ପ୍ଲଟ / ସର୍ଭେ ନମ୍ବର, ଗ୍ରାମ ଖୋଜନ୍ତୁ...",
    search_btn: "ଖୋଜନ୍ତୁ",
    voice_search_tooltip: "ଭଏସ ସର୍ଚ୍ଚ (ଓଡ଼ିଆରେ କୁହନ୍ତୁ)",
    listening: "ଶୁଣୁଛି... ଦୟାକରି କୁହନ୍ତୁ",
    advanced_filters: "ଫିଲ୍ଟର",
    owner_name: "ମାଲିକଙ୍କ ନାମ",
    survey_no: "ପ୍ଲଟ / ସର୍ଭେ ନମ୍ବର",
    village: "ଗ୍ରାମ",
    district: "ଜିଲ୍ଲା",
    state: "ରାଜ୍ୟ",
    land_area: "କ୍ଷେତ୍ରଫଳ (ଏକର/ଗୁଣ୍ଠ)",
    status: "ସ୍ଥିତି",
    view_details: "ବିବରଣୀ ଦେଖନ୍ତୁ",
    certified_ror: "ପ୍ରମାଣିତ ପଟ୍ଟା ରେକର୍ଡ (RoR)",
    gov_verified: "ସରକାର ଯାଞ୍ଚ କରିଛନ୍ତି",
    ai_extracted: "AI ସଂଗ୍ରହ କରିଛି",
    user_corrected: "ଅଧିକାରୀ ସଂଶୋଧନ କରିଛନ୍ତି",
    needs_verification: "ଯାଞ୍ଚ ଆବଶ୍ୟକ",
    lang_detected: "ଚିହ୍ନଟ ଭାଷା",
    legal_disclaimer: "ଆଇନଗତ ସୂଚନା: ମୂଳ ପଞ୍ଜୀକୃତ ଦଲିଲ ହିଁ ଆଇନଗତ ଭାବେ ଗ୍ରହଣୀୟ।"
  },
  as: {
    portal_title: "LandLens-AI",
    ministry_sub: "গ্ৰামোন্নয়ন মন্ত্ৰালয় • ভাৰত চৰকাৰ",
    search_records: "ৰেকৰ্ড বিচাৰক",
    registration_status: "পঞ্জীয়ন স্থিতি",
    cadastral_gis: "কেডেষ্ট্ৰেল জিআইএছ মানচিত্ৰ",
    officer_workspace: "বিষয়া কৰ্মক্ষেত্ৰ",
    login: "বিষয়া প্ৰৱেশ",
    logout: "প্ৰস্থান",
    hero_headline: "LandLens-AI",
    hero_sub: "AI-চালিত বহুভাষিক ভূমি নথি ডিজিটাইজেচন ব্যৱস্থা। প্ৰমাণিত পট্টা আৰু দাগ নম্বৰ বিচাৰক।",
    search_placeholder: "মাটিৰ গৰাকীৰ নাম, দাগ নম্বৰ, মৌজা বা গাঁও বিচাৰক...",
    search_btn: "বিচাৰক",
    voice_search_tooltip: "ভইচ চাৰ্ছ (অসমীয়াত কওক)",
    listening: "শুনি আছো... অনুগ্ৰহ কৰি কওক",
    advanced_filters: "ফিল্টাৰ",
    owner_name: "গৰাকীৰ নাম",
    survey_no: "দাগ / পট্টা নম্বৰ",
    village: "গাঁও / মৌজা",
    district: "জিলা",
    state: "ৰাজ্য",
    land_area: "মাটিৰ কালি (বিঘা/কঠা)",
    status: "স্থিতি",
    view_details: "বিৱৰণ চাওক",
    certified_ror: "প্ৰমাণিত পট্টা ৰেকৰ্ড (RoR)",
    gov_verified: "চৰকাৰীভাৱে পৰীক্ষিত",
    ai_extracted: "AI দ্বাৰা সংগ্ৰহ",
    user_corrected: "বিষয়াই সংশোধন কৰা",
    needs_verification: "পৰীক্ষাৰ প্ৰয়োজন",
    lang_detected: "চিনাক্ত ভাষা",
    legal_disclaimer: "আইনী জাননী: মূল পঞ্জীভুক্ত দলিলহে আইনগতভাৱে গ্ৰহণযোগ্য।"
  },
  ur: {
    portal_title: "LandLens-AI",
    ministry_sub: "وزارت دیہی ترقی • حکومت ہند",
    search_records: "ریکارڈ تلاش کریں",
    registration_status: "رجسٹریشن کی حیثیت",
    cadastral_gis: "اراضی نقشہ (GIS)",
    officer_workspace: "افسر ورک اسپیس",
    login: "افسر لاگ ان",
    logout: "لاگ آؤٹ",
    hero_headline: "LandLens-AI",
    hero_sub: "AI سے لیس کثیر لسانی اراضی ریکارڈ ڈیجیٹائزیشن۔ تصدیق شدہ کھتونی اور خسرہ ریکارڈ دیکھیں。",
    search_placeholder: "مالک زمین کا نام، خسرہ یا سروے نمبر، موضع یا ضلع تلاش کریں...",
    search_btn: "تلاش کریں",
    voice_search_tooltip: "صوتی تلاش (اردو میں بولیں)",
    listening: "سن رہے ہیں... بولیں",
    advanced_filters: "اضافی فلٹرز",
    owner_name: "مالک کا نام",
    survey_no: "خسرہ / سروے نمبر",
    village: "موضع / گاؤں",
    district: "ضلع",
    state: "ریاست",
    land_area: "رقبہ (ایکڑ)",
    status: "حیثیت",
    view_details: "تفصیلات دیکھیں",
    certified_ror: "تصدیق شدہ حق ملکیت ریکارڈ (کھتونی)",
    gov_verified: "حکومت سے تصدیق شدہ",
    ai_extracted: "AI کے ذریعے اخذ شدہ",
    user_corrected: "افسر کا ترمیم شدہ",
    needs_verification: "تصدیق درکار ہے",
    lang_detected: "شناخت شدہ زبان",
    legal_disclaimer: "قانونی نوٹس: اصل رجسٹرڈ دستاویز ہی قانونی طور پر معتبر ہے۔"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('sih_portal_lang') || 'en';
  });

  const changeLanguage = (code) => {
    setCurrentLang(code);
    localStorage.setItem('sih_portal_lang', code);
  };

  const t = (key) => {
    const langDict = UI_TRANSLATIONS[currentLang] || UI_TRANSLATIONS.en;
    return langDict[key] || UI_TRANSLATIONS.en[key] || key;
  };

  const getCurrentMeta = () => {
    return SUPPORTED_LANGUAGES.find(l => l.code === currentLang) || SUPPORTED_LANGUAGES[0];
  };

  return (
    <LanguageContext.Provider value={{ currentLang, changeLanguage, t, getCurrentMeta, supportedLanguages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return ctx;
};
